### ISSUE TITLE
HOT Exports is down again

### ISSUE THREAD

**Issue by severinmenard** [hotosm/hot-exports#96]
Any new run that is started eventually fails.

**Comment by dodobas** [comment]
why?

**Comment by severinmenard** [comment]
I do not know, there is a "Error in CDE" message, maybe lack of disk space?
See http://export.hotosm.org/en/jobs/6352 as an example.

**Comment by dodobas** [comment]
well, the error seems to be related to the mkgmap utility.... 
```
java -Xmx3096m -jar /home/hot/mkgmap/mkgmap.jar --route --index -n 80000111 --description='central_african_republic_whole_country_r_publique_centrafricaine_pays_entier' --gmapsupp --draw-priority=99 --family-id=3456 --nsis --series-name='central_african_republic_whole_country_r_publique_centrafricaine_pays_entier' --output-dir=var/runs/tmp/023803-gmapsupp var/runs/023803/rawdata.osm.pbf
Time started: Sun Dec 07 20:55:03 CET 2014
java.lang.IllegalArgumentException: Description is too long (max 50)
	at uk.me.parabola.imgfmt.sys.ImgHeader.setDescription(ImgHeader.java:312)
	at uk.me.parabola.imgfmt.sys.ImgHeader.createHeader(ImgHeader.java:163)
	at uk.me.parabola.imgfmt.sys.ImgFS.createInitFS(ImgFS.java:285)
	at uk.me.parabola.imgfmt.sys.ImgFS.createFs(ImgFS.java:111)
	at uk.me.parabola.imgfmt.sys.ImgFS.createFs(ImgFS.java:90)
	at uk.me.parabola.imgfmt.app.map.Map.createMap(Map.java:97)
	at uk.me.parabola.mkgmap.main.MapMaker.makeMap(MapMaker.java:111)
	at uk.me.parabola.mkgmap.main.MapMaker.makeMap(MapMaker.java:69)
	at uk.me.parabola.mkgmap.main.Main$1.call(Main.java:243)
	at uk.me.parabola.mkgmap.main.Main$1.call(Main.java:239)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
Exiting - if you want to carry on regardless, use the --keep-going option
Time finished: Sun Dec 07 20:55:54 CET 2014
Total time taken: 50731ms
gzip < var/runs/tmp/023803-gmapsupp/gmapsupp.img > var/runs/023803/gmapsupp.img.gz
child exited with value 2
rm -rf var/runs//tmp/023803-gmapsupp
```

so .. ```central_african_republic_whole_country_r_publique_centrafricaine_pays_entier``` is longer than 50 characters, which is a limit of mkgmap utility for creating garmin maps

job title *Central African Republic, whole country/République centrafricaine, pays entier* is too long ...

**Comment by mikelmaron** [comment]
good debugging! so I think we should file another bug report, for the hot export to not allow names longer than 50 characters; but in the mean time, simply keep the names shorter

**Comment by severinmenard** [comment]
It affects any kind of job, even the ones with shorter names. Eg: http://export.hotosm.org/fr/jobs/11826

**Comment by dodobas** [comment]
that job has a different error...
```
running transformation: tagtransform-281
spatialite var/runs/025990/test_hddm_traduction_transformation_4.sqlite < web/public/uploads/tagtransform-281
SQL error near line 1: near "ï»¿alter": syntax error
SQL error near line 2: no such column: bati
SQL error near line 3: near "drop": syntax error
child exited with value 3
```

not sure what is that exactly, but it does have something to do with *tagtransform* process
